[metadata]
	version = "1.0.0"
	name = "turn_right"
	duration = 0.0
	looping = true

[layers]
	default = 1.0

[default.shoulders.rotation]
	"0.0000" = {to = [-0.0, 10.0, -0.0], interpolation = ["both", "linear"]}

[default.tailLower.rotation]
	"0.0000" = {to = [-0.0, -12.5, -0.0], interpolation = ["both", "linear"]}

[default.rightUpperArm.rotation]
	"0.0000" = {to = [-10.0, 0.0, -0.0], interpolation = ["both", "linear"]}

[default.rightLowerArm.rotation]
	"0.0000" = {to = [10.0, 0.0, -0.0], interpolation = ["both", "linear"]}

[default.lowerBody.rotation]
	"0.0000" = {to = [-0.0, 5.0, 5.0], interpolation = ["both", "linear"]}

[default.upperBody.rotation]
	"0.0000" = {to = [-0.0, 10.0, -0.0], interpolation = ["both", "linear"]}

[default.belly1.rotation]
	"0.0000" = {to = [-0.0, -6.0, -0.0], interpolation = ["both", "linear"]}

[default.neck.rotation]
	"0.0000" = {to = [-0.0, 10.0, 5.0], interpolation = ["both", "linear"]}

[default.neck1.rotation]
	"0.0000" = {to = [-0.0, 10.0, 5.0], interpolation = ["both", "linear"]}

[default.head.rotation]
	"0.0000" = {to = [0.44529, 3.68972, 0.8722], interpolation = ["both", "linear"]}

[default.tail1.rotation]
	"0.0000" = {to = [-0.0, -10.0, -2.5], interpolation = ["both", "linear"]}

[default.tail2.rotation]
	"0.0000" = {to = [-0.0, -10.0, -2.5], interpolation = ["both", "linear"]}

[default.rightThigh.position]
	"0.0000" = {to = [0.0, 0.0, 0.0], interpolation = ["both", "linear"]}
[default.rightThigh.rotation]
	"0.0000" = {to = [-0.0, -5.0, -10.0], interpolation = ["both", "linear"]}

[default.leftFoot.rotation]
	"0.0000" = {to = [-0.0, 0.0, -5.0], interpolation = ["both", "linear"]}

[default.tail3.rotation]
	"0.0000" = {to = [-0.0, -10.0, -2.5], interpolation = ["both", "linear"]}

[default.rightLeg.rotation]
	"0.0000" = {to = [-0.0, 0.0, 5.0], interpolation = ["both", "linear"]}

[default.hips.rotation]
	"0.0000" = {to = [-0.0, 5.0, 5.0], interpolation = ["both", "linear"]}

[default.tail4.rotation]
	"0.0000" = {to = [-0.0, -10.0, -2.5], interpolation = ["both", "linear"]}

[default.leftThigh.position]
	"0.0000" = {to = [0.0, -0.5, 0.0], interpolation = ["both", "linear"]}
[default.leftThigh.rotation]
	"0.0000" = {to = [-0.0, -5.0, -0.0], interpolation = ["both", "linear"]}
