name = "tyrannosaurus_adult_v2"

[component.model]
model = "game:model_variant:tyrannosaurus_adult_v2_default"

[component.transformation]
position = [1.25, 0, -30]
scale = [1, 1, 1]

[component.animation]
animation = "game:tv_animation:walk"
